[{'allText': [' APW20001001.2021.0521 ',
              ' NEWS STORY ',
              'newswire',
              ' 2000-10-01 20:56:35 ',
              '\n',
              ' Egypt-Assad ',
              '\nSyrian President Travels To Egypt \n'],
  'num': 0,
  'offset': 114,
  'paragraphs': ["\nCAIRO, Egypt (AP) _ In his foreign policy debut as Syria's\npresident, Bashar Assad met Sunday with Egyptian President Hosni\nMubarak in talks on Mideast peace and the escalating violence in the\nPalestinian territories. ",
                 'Assad, on his first trip abroad since becoming president in July,\nalso dealt with the issue of Iraq in the talks with Mubarak,\nEgyptian Foreign Minister Amr Mussa said. ',
                 "The Syrian leader's visit came on a fourth day of clashes that have\nraged in the West Bank, Gaza Strip and Jerusalem, leaving more than\ntwo dozen Palestinians dead. ",
                 "``There is complete agreement (between Mubarak and Assad) as to the\nseriousness of the situation and that the negative repercussions\nwould adversely effect the peace process, which is in itself in a\nvery precarious state,'' Moussa said. ",
                 "Assad, 35, has focused on domestic issues since his father, Hafez\nAssad, died in June after 30 years in power. He has taken steps to\nmodernize his nation's bureaucracy and revive its stagnant economy. ",
                 "``This was the first meeting of the first visit of President Bashar\nAssad after the funeral of his father, so it was only normal for the\ndiscussions to have a general tone ... in addition to certain\nspecifics of special importance to both countries and the Arab\nworld,'' Moussa said. ",
                 'The late Syrian president rarely traveled abroad. In his last few\nyears, however, he had sent Bashar, educated as an eye doctor, on\nforeign trips as part of his grooming to become president. ',
                 "Prospects appear dim for progress on either the Syrian or\nPalestinian peace track. The deadlock in Palestinian-Israeli talks\nis exacerbated by the worst violence in four years. Syria's\ngovernment-run media said last week that no progress could be\nexpected now because of the U.S. elections and Israeli Prime\nMinister Ehud Barak's precarious situation as leader of a minority\ngovernment. ",
                 'Syrian-Israeli peace negotiations broke down in January, with Syria\ndemanding a full withdrawal from the Golan Heights, a strategic\nplateau captured by Israel in 1967. Israel insists on waiting to\nsettle borders until it knows what it will gain by returning Golan\nland. ',
                 "Assad has made it clear he intends to follow his father's course in\nany negotiations with Israel. ",
                 'Mubarak and Assad met after a week when Russia, France, Jordan and\nYemen sent planes to Baghdad, challenging U.N. sanctions imposed on\nIraq after its 1990 invasion of Kuwait. Iraq is hoping other Arab\ncountries will follow, despite U.S. complaints, easing its\nisolation. ',
                 'Moussa said the presidents discussed the situation in Iraq and would\nreturn to it Monday. However, he would not comment on whether Syria\nand Egypt were planning to send planes to Baghdad. ',
                 "Egypt and Syria are on good terms, but they have had their\ndifferences. Hafez Assad's attempts to rally Arab leaders to present\na unified front against Israel gained little ground. He derided\nEgypt for signing a peace treaty with Israel in 1979. \n"]}]
